
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import static java.lang.System.in;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;



/**
 *
 * @author rayan
 */
public class ClientGUI extends javax.swing.JFrame {
    
    private static final int SERVER_PORT = 5000;

    private static Socket socket;
    private static BufferedReader in_fromServer;
    private static PrintWriter out_toServer;
    private static boolean Connected = false;
    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
        ButtonHandler handler = new ButtonHandler();
        registerBtn.addActionListener(handler);
        loginBtn.addActionListener(handler);
        reserveBtn.addActionListener(handler);
        cancelBtn.addActionListener(handler);
        profileBtn.addActionListener(handler);
        exitBtn.addActionListener(handler);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        registerBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        reserveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        connectBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImages(null);

        outputArea.setEditable(false);
        outputArea.setColumns(20);
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        registerBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        loginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        reserveBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        reserveBtn.setText("Reserve");

        cancelBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        profileBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        profileBtn.setText("View Profile");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 0, 0));
        exitBtn.setText("Exit");
        exitBtn.setPreferredSize(new java.awt.Dimension(75, 25));

        connectBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        connectBtn.setForeground(new java.awt.Color(0, 204, 0));
        connectBtn.setText("Connect");
        connectBtn.setPreferredSize(new java.awt.Dimension(75, 25));
        connectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reserveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(connectBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(connectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profileBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginBtnActionPerformed

    private void connectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectBtnActionPerformed
           connectToServer();
    }//GEN-LAST:event_connectBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }
    
private void connectToServer() {
        try {
            String SERVER_ADDRESS = JOptionPane.showInputDialog("Enter Server IP:");
            if (SERVER_ADDRESS == null || SERVER_ADDRESS.trim().isEmpty()) return;
            socket = new Socket(SERVER_ADDRESS.trim(), SERVER_PORT);
            in_fromServer = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            out_toServer = new PrintWriter(socket.getOutputStream(), true);

            Thread listener = new Thread(new ServerListenerGUI(in_fromServer, outputArea));
            listener.start();
            

            outputArea.append("Connected to server.\n");
            Connected = true;
        } catch (IOException e) {
            outputArea.append("Failed to connect.\n");
        }
    }

private void Register() {
        String username = JOptionPane.showInputDialog("Enter username:");
        String password = JOptionPane.showInputDialog("Enter password:");
        sendCommand(1);
        sendCommand(username+" ");
        sendCommand(password+" ");
    }

    private void login() {
        String username = JOptionPane.showInputDialog("Enter username:");
        String password = JOptionPane.showInputDialog("Enter password:");
        sendCommand(2);
        sendCommand(username+" ");
        sendCommand(password+" ");
    }

    private void reserve() {
        String slot = JOptionPane.showInputDialog("Enter slot (e.g., Room8-Friday-11AM):");
        
        sendCommand(3);
        sendCommand(slot);
    }

    private void cancel() {
        sendCommand(4);
        String choice = JOptionPane.showInputDialog("Enter reservation number to cancel (check output list):");
        if (choice != null) {
            sendCommand(choice);
        }
    }

    private void sendCommand(String cmd) {
        cmd = cmd+" ";
        if (out_toServer != null) out_toServer.println(cmd);
    }
    private void sendCommand(int cmd) {
        if (out_toServer != null) out_toServer.println(cmd);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton cancelBtn;
    private static javax.swing.JButton connectBtn;
    private static javax.swing.JButton exitBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JButton loginBtn;
    private static javax.swing.JTextArea outputArea;
    private static javax.swing.JButton profileBtn;
    private static javax.swing.JButton registerBtn;
    private static javax.swing.JButton reserveBtn;
    // End of variables declaration//GEN-END:variables
private class ButtonHandler implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent evt) {
            if (Connected == true){
                Object source = evt.getSource();
                if (source == registerBtn) Register();
                else if (source == loginBtn) login();
                else if (source == reserveBtn) reserve();
                else if (source == cancelBtn) cancel();
                else if (source == profileBtn) sendCommand(5);
                else if (source == exitBtn) {
                    sendCommand("6");
                    outputArea.append("You have disconnected.\n");
                    Connected = false;
                    System.out.println("Client closed the GUI and disconnected.");
                    try {
                        if (socket != null) socket.close();
                }   catch (IOException e) {
                        e.printStackTrace();
                }
            }
            }
            else {
            outputArea.append("Connect First!\n");
            }
        }
    }
}
class ServerListenerGUI implements Runnable {
    private BufferedReader in_fromServer;
    private JTextArea outputArea;

    public ServerListenerGUI(BufferedReader in_fromServer, JTextArea outputArea) {
        this.in_fromServer = in_fromServer;
        this.outputArea = outputArea;
    }

    @Override
    public void run() {
        try {
            String serverMsg;
            while ((serverMsg = in_fromServer.readLine()) != null) {
                outputArea.append(serverMsg + "\n");
            }
        } catch (IOException e) {
            outputArea.append("Disconnected from server.\n");
            
            
        }
    }
}